// <auto-generated />
using System;
using MagicVilla_Api.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230317145707_AlimentarTablaVilla")]
    partial class AlimentarTablaVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_Api.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenida = "",
                            Detalle = "Detalle de la villa",
                            FechaActualizacion = new DateTime(2023, 3, 17, 9, 57, 7, 13, DateTimeKind.Local).AddTicks(6498),
                            FechaCreacion = new DateTime(2023, 3, 17, 9, 57, 7, 13, DateTimeKind.Local).AddTicks(6485),
                            ImageUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Villa real",
                            Ocupantes = 5,
                            Tarifa = 200100.0
                        },
                        new
                        {
                            Id = 2,
                            Amenida = "",
                            Detalle = "Detalle de la villa",
                            FechaActualizacion = new DateTime(2023, 3, 17, 9, 57, 7, 13, DateTimeKind.Local).AddTicks(6501),
                            FechaCreacion = new DateTime(2023, 3, 17, 9, 57, 7, 13, DateTimeKind.Local).AddTicks(6501),
                            ImageUrl = "",
                            MetrosCuadrados = 60,
                            Nombre = "Villa premiun vista a la playa",
                            Ocupantes = 4,
                            Tarifa = 500000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
